### ISSUE TITLE
New Ruby version needed for Heroku

### ISSUE THREAD

**Issue by frankmeeuwsen** [barryf/webhook-mentions#2]
I deployed your script to Heroku, but during install it gave the error that the named version of Ruby (2.3.1) is not supported by Heroku. I'd love to use your script for my webmentions but I'm stuck, since I'm not that fluent in Ruby and the  dependencies. Is there any way you can help?

**Comment by barryf** [comment]
Ah, it looks like I need to update the version, probably to 2.4.x. I'll take a look.

**Comment by barryf** [comment]
I've tested a deploy to Heroku and the build now completes 👍

**Comment by frankmeeuwsen** [comment]
Hi, thanks for responding so fast! I tested the new version but I still get all sorts of errors after deployment. So when I actually send a webmention when my page is built, the logfile on Heroku shows a lot errors in the dependencies. I've added the logfile for your convenience. I hope you can help me out here some more?
[sending-webmentions-dtd-logs-1540137504757.txt](https://github.com/barryf/webhook-mentions/files/2499362/sending-webmentions-dtd-logs-1540137504757.txt)

**Comment by barryf** [comment]
Looking at your original post, I think it's because you're using capitals and spaces in your filenames. I'm not sure if that's correct usage or not, but it's tripping up the filename regex. I've adapted the source to allow for your use case. Hopefully that will work now.

**Comment by frankmeeuwsen** [comment]
I just did another test. Unfortunately not as planned. Thing is, it might happen there are spaces and capitals in the filename. But the URL is constructed a bit different from what I can tell what is in the logfile now. For instance, the latest test post is https://diggingthedigital.com/test-drie/ but the logfile on Heroku says it's https://diggingthedigital.com//test%20drie/ which gives a 404. 
I will make try it again but not on my main blog so I can test some more. Thanks for your help so far. I really want to get webmentions working but I don't have the chops to do it all myself.

[sending-webmentions-dtd-logs-1540148068233.txt](https://github.com/barryf/webhook-mentions/files/2499498/sending-webmentions-dtd-logs-1540148068233.txt)

**Comment by barryf** [comment]
Try using hyphens instead of spaces for your files e.g. `2018-10-21-test-drie.md`. I think that may help.

**Comment by frankmeeuwsen** [comment]
I'm testing it right now with a testblog with some fake text and tests to https://webmention.rocks. It seems to send something out but I don't see any results on the other end. I will test some more. I'l take a look how I can make sure all filenames always have hyphen before they are commited. It is cleaner, that is true.

**Comment by barryf** [comment]
Awesome! My pleasure. Pleased it works for you. 😎

**Comment by frankmeeuwsen** [comment]
Check the picture I just added on https://diggingthedigital.com/test-vijf/. Celebrating with a beer. I also have the hyphen-thing solved with a local script so that's all good. This issue is now _really_ closed.
